"""Add user_answers column

Revision ID: b8e430575fb7
Revises: 194558da7986
Create Date: 2026-04-06 21:21:56.713759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8e430575fb7'
down_revision: Union[str, None] = '194558da7986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_results', sa.Column('user_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_results', 'user_answers')
    # ### end Alembic commands ###
